import type { CompletionResult, CompletionContext } from '@codemirror/autocomplete';

// ── Language → snippet mappings ─────────────────────────────────────────────

const SNIPPETS: Record<string, string[]> = {
  javascript: [
    'console.log()',
    'console.error()',
    'console.warn()',
    'import ',
    'import * as ',
    'import {  } from \'\'',
    'export default ',
    'export const ',
    'export function ',
    'async function () {}',
    'const  = () => {}',
    'const  = async () => {}',
    'const { useState } = require("react")',
    'const { useEffect } = require("react")',
    'const { useRef } = require("react")',
    'if (  ) {}',
    'if (  ) {} else {}',
    'for (let i = 0; i < ; i++) {}',
    'try {  } catch (err) {  }',
    'class  {  }',
    'const arr = [].map()',
    'const arr = [].filter()',
    'const arr = [].reduce()',
    'Promise.resolve()',
    'new Promise((resolve, reject) => {})',
    'module.exports = ',
  ],
  typescript: [
    'console.log()',
    'console.error()',
    'import type ',
    'import {  } from \'\'',
    'export default ',
    'export const ',
    'export function ',
    'export type ',
    'export interface ',
    'interface  {  }',
    'type  = ',
    'enum  {  }',
    'async function (): Promise<{}> {}',
    'const  = ():  => {}',
    'const  = async (): Promise<{}> => {}',
    'const [state, setState] = useState<{}>({})',
    'if (  ) {}',
    'for (let i = 0; i < ; i++) {}',
    'try {  } catch (err) {  }',
    'class  {  }',
    'record<string, unknown>',
    'Partial<{}>',
    'Readonly<{}>',
  ],
  python: [
    'def ():',
    'def __init__(self):',
    'class :',
    'import ',
    'from  import ',
    'if __name__ == \'__main__\':',
    'if :',
    'elif :',
    'for  in :',
    'while :',
    'try:',
    'except Exception as e:',
    'with open(\'\', \'r\') as f:',
    'with open(\'\', \'w\') as f:',
    'print()',
    'return ',
    'self.',
    'lambda : ',
    'list(range())',
    'dict()',
    'set()',
    '# TODO: ',
    '"""docstring"""',
    'raise ValueError()',
  ],
  go: [
    'package ',
    'import (',
    'import "',
    'func () {}',
    'func () error {',
    'func () (, error) {',
    'func (receiver *) () {}',
    'type  struct {',
    'interface {}',
    'var  ',
    'const  = ',
    'if  {',
    'for  {',
    'for i := 0; i < ; i++ {',
    'range ',
    'switch  {',
    'select {',
    'go ()',
    'chan ',
    'make([])',
    'make(map[)])',
    'fmt.Println()',
    'fmt.Printf("", )',
    'log.Printf()',
    'return nil',
    'return , nil',
    'return , err',
  ],
  css: [
    'display: flex;',
    'display: grid;',
    'display: block;',
    'display: inline-block;',
    'display: none;',
    'position: relative;',
    'position: absolute;',
    'position: fixed;',
    'position: sticky;',
    'margin: 0 auto;',
    'padding: ',
    'width: 100%;',
    'height: 100%;',
    'background: #',
    'background-color: #',
    'color: #',
    'font-size: ',
    'line-height: ',
    'border: 1px solid #',
    'border-radius: ',
    'box-shadow: 0 2px 4px rgba(0,0,0,0.1);',
    'transition: all 0.3s ease;',
    '@media (max-width: ) {',
    '@media (min-width: ) {',
    '@media (prefers-color-scheme: dark) {',
    '@keyframes  {',
    '@font-face {',
    'justify-content: center;',
    'align-items: center;',
    'gap: ',
    'flex-direction: column;',
    'grid-template-columns: ;',
    'overflow: hidden;',
    'cursor: pointer;',
    'opacity: ;',
    'z-index: ;',
  ],
  html: [
    '<div></div>',
    '<span></span>',
    '<p></p>',
    '<a href=""></a>',
    '<img src="" alt="" />',
    '<ul><li></li></ul>',
    '<ol><li></li></ol>',
    '<section></section>',
    '<header></header>',
    '<footer></footer>',
    '<nav></nav>',
    '<main></main>',
    '<article></article>',
    '<button type="button"></button>',
    '<input type="text" />',
    '<form></form>',
    '<table></table>',
    '<thead></thead>',
    '<tbody></tbody>',
    '<script></script>',
    '<style></style>',
    '<link rel="stylesheet" href="" />',
    '<meta name="" content="" />',
    '<h1></h1>',
    '<h2></h2>',
    '<h3></h3>',
    '<br />',
    '<hr />',
  ],
  json: [
    '"": ""',
    '"": 0',
    '"": true',
    '"": null',
    '"": []',
    '"": {}',
  ],
  rust: [
    'fn () {}',
    'pub fn () {}',
    'pub struct  {',
    'pub enum  {',
    'impl  {',
    'let mut  = ;',
    'let  = ;',
    'const :  = ;',
    'use ',
    'mod ;',
    'if  {',
    'match  {',
    'for  in  {',
    'while  {',
    'loop {',
    'println!("");',
    'Vec::new()',
    'HashMap::new()',
    'Option<{}>',
    'Result<{}, Error>',
    'String::from("")',
    '.unwrap()',
    '.expect("")',
    '.clone()',
    '.to_string()',
    '#[derive(Debug)]',
    '#[derive(Clone)]',
    'return Ok(());',
    'return Err();',
  ],
  shell: [
    '#!/bin/bash',
    '#!/bin/sh',
    'if [  ]; then',
    'for  in ; do',
    'while [  ]; do',
    'case  in',
    'function () {',
    'echo ""',
    'echo "Error: " >&2',
    'exit 1',
    'read -p "" ',
    'local =""',
    'export =""',
    'source ',
    'chmod +x ',
    'mkdir -p ',
    'cp -r  ',
    'mv  ',
    'rm -rf ',
    'grep -r "" ',
    'find . -name ""',
    'sed -i \'s///g\' ',
    'awk \'{print }\' ',
    'curl -s ',
  ],
};

/** Map common file extensions to language keys */
const EXT_TO_LANG: Record<string, string> = {
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  py: 'python',
  pyw: 'python',
  go: 'go',
  css: 'css',
  scss: 'css',
  less: 'css',
  html: 'html',
  htm: 'html',
  json: 'json',
  rs: 'rust',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
};

/**
 * Snippet autocompleter.
 *
 * Returns language-specific code snippets based on the current file type.
 */
export function createSnippetCompleter(
  getActiveFilePath: () => string | null,
  onLanguageChanged: (cb: (info: { languageId: string }) => void) => { dispose(): void },
): (context: CompletionContext) => CompletionResult | null {
  let currentLang = detectLanguage(getActiveFilePath());

  onLanguageChanged(({ languageId }) => {
    currentLang = languageId.toLowerCase();
  });

  return (context: CompletionContext): CompletionResult | null => {
    const langSnippets = SNIPPETS[currentLang];
    if (!langSnippets) return null;

    const { pos, state } = context;
    const word = state.wordAt(pos);
    const from = (word as any)?.from ?? pos;
    const filterText = (word as any)?.text ?? '';

    if (filterText.length < 2) return null;

    const filtered = langSnippets.filter((s) =>
      s.toLowerCase().startsWith(filterText.toLowerCase()),
    );

    if (filtered.length === 0) return null;

    return {
      from,
      options: filtered.map((snippet) => ({
        label: snippet,
        type: 'text' as const,
        boost: 2,
      })),
    };
  };
}

function detectLanguage(filePath: string | null): string {
  if (!filePath) return 'javascript';
  const ext = filePath.split('.').pop()?.toLowerCase() ?? '';
  return EXT_TO_LANG[ext] ?? 'javascript';
}
